### ISSUE TITLE
ToDo Goal 1

### ISSUE THREAD

**Issue by PCBaum** [PCBaum/PnS_STM32_Wavedetection#1]
- [ ] Build Styrofoam float (for testing), or better, a watertight floating case for the sensor
- [ ] Read out Accelerometer data, save some in a buffer
- [ ] Determine the average of the sensor data
- [ ] compare absolute values and determine local maximums
- [ ] if the local maximum is signifficantly more than normal and somewhat continuous compared to previious and following states we have a wave
- [ ] send result with serial over USB

**Comment by PCBaum** [comment]
done
