### ISSUE TITLE
ToDo Goal 3

### ISSUE THREAD

**Issue by PCBaum** [PCBaum/PnS_STM32_Wavedetection#3]
- [ ] Define Sleep state (turn off sensors etc)
- [ ] Create *Interrupt* to *wake up* the Microcontroller every hour or so
- [ ] Wakeup procedure
- [ ] Create *Timer* to put Microcontroller back to sleep after enough measurement have been made
