### ISSUE TITLE
ToDo Goal 6

### ISSUE THREAD

**Issue by PCBaum** [PCBaum/PnS_STM32_Wavedetection#6]
- [ ] make a *lookup tabel* to classify the different waveheigths
- [ ] compute waveheight
- [ ] save the current waveheight to 2.
- [ ] adjust output functions (serial, WiFi)

**Comment by PCBaum** [comment]
adjuted the program to just calculate the waveheight
