### ISSUE TITLE
ToDo Goal 8

### ISSUE THREAD

**Issue by PCBaum** [PCBaum/PnS_STM32_Wavedetection#8]
- [ ] connect an external waterproof temperature sensor
- [ ] read out its values and compute temperature
- [ ] add result to the data stored in 2.
- [ ] adjust output functions (serial, WiFi)
