### ISSUE TITLE
ToDo Goal 9

### ISSUE THREAD

**Issue by PCBaum** [PCBaum/PnS_STM32_Wavedetection#9]
- [ ] Connect an external light sensor
- [ ] read out its values and compute the luminosity
- [ ] add result to data stored in 2
- [ ] adjust output functions (serial, WiFi)
